# Generated by Django 6.1.1 on 2026-09-12 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1)),
                ('age', models.IntegerField()),
                ('registered_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='xrays/%Y/%m/%d/')),
                ('taken_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.patient')),
            ],
        ),
    ]
